/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewChatRouteImport } from './routes/new-chat'
import { Route as IdRouteImport } from './routes/$id'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyAccountIndexRouteImport } from './routes/my-account/index'
import { Route as MyAccountEditPasswordRouteImport } from './routes/my-account/edit-password'
import { Route as authThankYouRouteImport } from './routes/(auth)/thank-you'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authGoodbyeRouteImport } from './routes/(auth)/goodbye'
import { Route as authForgotSentRouteImport } from './routes/(auth)/forgot-sent'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authVerifyIndexRouteImport } from './routes/(auth)/verify/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'

const NewChatRoute = NewChatRouteImport.update({
  id: '/new-chat',
  path: '/new-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IdRoute = IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAccountIndexRoute = MyAccountIndexRouteImport.update({
  id: '/my-account/',
  path: '/my-account/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAccountEditPasswordRoute = MyAccountEditPasswordRouteImport.update({
  id: '/my-account/edit-password',
  path: '/my-account/edit-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authThankYouRoute = authThankYouRouteImport.update({
  id: '/(auth)/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authGoodbyeRoute = authGoodbyeRouteImport.update({
  id: '/(auth)/goodbye',
  path: '/goodbye',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotSentRoute = authForgotSentRouteImport.update({
  id: '/(auth)/forgot-sent',
  path: '/forgot-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyIndexRoute = authVerifyIndexRouteImport.update({
  id: '/(auth)/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/new-chat': typeof NewChatRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/forgot-sent': typeof authForgotSentRoute
  '/goodbye': typeof authGoodbyeRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/thank-you': typeof authThankYouRoute
  '/my-account/edit-password': typeof MyAccountEditPasswordRoute
  '/my-account': typeof MyAccountIndexRoute
  '/login': typeof authLoginIndexRoute
  '/verify': typeof authVerifyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/new-chat': typeof NewChatRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/forgot-sent': typeof authForgotSentRoute
  '/goodbye': typeof authGoodbyeRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/thank-you': typeof authThankYouRoute
  '/my-account/edit-password': typeof MyAccountEditPasswordRoute
  '/my-account': typeof MyAccountIndexRoute
  '/login': typeof authLoginIndexRoute
  '/verify': typeof authVerifyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/new-chat': typeof NewChatRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/forgot-sent': typeof authForgotSentRoute
  '/(auth)/goodbye': typeof authGoodbyeRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/thank-you': typeof authThankYouRoute
  '/my-account/edit-password': typeof MyAccountEditPasswordRoute
  '/my-account/': typeof MyAccountIndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/verify/': typeof authVerifyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$id'
    | '/new-chat'
    | '/forgot-password'
    | '/forgot-sent'
    | '/goodbye'
    | '/reset-password'
    | '/signup'
    | '/thank-you'
    | '/my-account/edit-password'
    | '/my-account'
    | '/login'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$id'
    | '/new-chat'
    | '/forgot-password'
    | '/forgot-sent'
    | '/goodbye'
    | '/reset-password'
    | '/signup'
    | '/thank-you'
    | '/my-account/edit-password'
    | '/my-account'
    | '/login'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/$id'
    | '/new-chat'
    | '/(auth)/forgot-password'
    | '/(auth)/forgot-sent'
    | '/(auth)/goodbye'
    | '/(auth)/reset-password'
    | '/(auth)/signup'
    | '/(auth)/thank-you'
    | '/my-account/edit-password'
    | '/my-account/'
    | '/(auth)/login/'
    | '/(auth)/verify/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdRoute: typeof IdRoute
  NewChatRoute: typeof NewChatRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authForgotSentRoute: typeof authForgotSentRoute
  authGoodbyeRoute: typeof authGoodbyeRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignupRoute: typeof authSignupRoute
  authThankYouRoute: typeof authThankYouRoute
  MyAccountEditPasswordRoute: typeof MyAccountEditPasswordRoute
  MyAccountIndexRoute: typeof MyAccountIndexRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
  authVerifyIndexRoute: typeof authVerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new-chat': {
      id: '/new-chat'
      path: '/new-chat'
      fullPath: '/new-chat'
      preLoaderRoute: typeof NewChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id': {
      id: '/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-account/': {
      id: '/my-account/'
      path: '/my-account'
      fullPath: '/my-account'
      preLoaderRoute: typeof MyAccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-account/edit-password': {
      id: '/my-account/edit-password'
      path: '/my-account/edit-password'
      fullPath: '/my-account/edit-password'
      preLoaderRoute: typeof MyAccountEditPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/thank-you': {
      id: '/(auth)/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof authThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/goodbye': {
      id: '/(auth)/goodbye'
      path: '/goodbye'
      fullPath: '/goodbye'
      preLoaderRoute: typeof authGoodbyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-sent': {
      id: '/(auth)/forgot-sent'
      path: '/forgot-sent'
      fullPath: '/forgot-sent'
      preLoaderRoute: typeof authForgotSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify/': {
      id: '/(auth)/verify/'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof authVerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdRoute: IdRoute,
  NewChatRoute: NewChatRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authForgotSentRoute: authForgotSentRoute,
  authGoodbyeRoute: authGoodbyeRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignupRoute: authSignupRoute,
  authThankYouRoute: authThankYouRoute,
  MyAccountEditPasswordRoute: MyAccountEditPasswordRoute,
  MyAccountIndexRoute: MyAccountIndexRoute,
  authLoginIndexRoute: authLoginIndexRoute,
  authVerifyIndexRoute: authVerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
